apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
      - name: to-do
        image: carlosm04/bootcamp:version
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /readiness
            port: 4444
          initialDelaySeconds: 20
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 4444
          initialDelaySeconds: 20
          periodSeconds: 3

